#服务名
spring:
  application:
    name: yHApp
  redis:
    host: 182.92.129.244 # Redis服务器地址
    database: 0 #Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）
    password: yh007xx
  profiles:
    active: pro
  rabbitmq:
    host: 182.92.129.244
    username: yh007
    password: yh007xx

pgsql:
  datasource:
    url: jdbc:postgresql://182.92.129.244:5432/postgres
    username: postgres
    password: yh007xx
    driver-class-name: org.postgresql.Driver
    maxActive: 50
    initialSize: 10
    maxWait: 60000
    minIdle: 6
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

#spring自带的slf4j门面+log4j实现日志,如果识别到了logback.xml文件就用xml配置
#logging:
#  level:
#    root: info
#  path: D:\springboot.log
logging:
  config: classpath:log4j2.xml

#注入javaBean，@ConfigurationProperties(prefix = "person")，@PropertySource：加载指定的配置文件；
person:
  lastName: hello
  age: 18
  boss: false
  birth: 2017/12/12
  maps: {k1: v1,k2: 12}
  lists:
    - lisi
    - zhaoliu
  dog:
    name: 小狗
    age: 12


quartz:
  enable: false
